app:
  name: "My Application"
  version: "1.0.0"
  environment: "development"

database:
  host: "localhost"
  port: 5432
  name: "myapp_db"
  user: "db_user"
  max_connections: 100
  timeout: 30

logging:
  level: "INFO"
  file: "app.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

email:
  smtp_server: "smtp.company.com"
  smtp_port: 587
  sender: "noreply@company.com"
  template_dir: "templates"

features:
  cache_enabled: true
  max_retries: 3
  batch_size: 1000